[pytest]
filterwarnings =
    ignore::FutureWarning:google.api_core.*
    ignore::FutureWarning:google.auth.*
    ignore::FutureWarning:google.oauth2.*
    ignore::FutureWarning:geo_service.*
    ignore::DeprecationWarning:matplotlib.*
    ignore::PIL.Image.DecompressionBombWarning
